### PR TITLE
Added optional variable mergeParams to router parameters to be merged 

### PR DESCRIPTION
**Pull request by fadeenk**
when using multiple nested routers

### CODE REVIEW

**Comment by developit** [comment]
Looks good, but would it be possible to pass this as `route.mergeParams` instead of adding a second argument?

**Comment by developit** [comment]
Looks great! Merging.

**Comment by developit** [comment]
@fadeenk Released as `0.6.0`. Thanks.

**Comment by fadeenk** [comment]
thank you for the quick feedback and approval

**Comment by developit** [comment]
No problem :)

**Pull request merged**
